// Centralized socket event names keep the realtime contract consistent across modules.
export const CLIENT_EVENTS = {
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  SHOW_PRODUCT: "SHOW_PRODUCT",
  CLEAR_PRODUCT: "CLEAR_PRODUCT",
  START_DISCOUNT: "START_DISCOUNT",
  STOP_DISCOUNT: "STOP_DISCOUNT",
} as const;

export const SERVER_EVENTS = {
  ROOM_CREATED: "ROOM_CREATED",
  ROOM_JOINED: "ROOM_JOINED",
  ROOM_UPDATED: "ROOM_UPDATED",
  ROOM_ERROR: "ROOM_ERROR",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_CLEARED: "PRODUCT_CLEARED",
  PRODUCT_ERROR: "PRODUCT_ERROR",
  DISCOUNT_UPDATED: "DISCOUNT_UPDATED",
  DISCOUNT_CLEARED: "DISCOUNT_CLEARED",
  DISCOUNT_ERROR: "DISCOUNT_ERROR",
} as const;

export enum RoomErrorCode {
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_FULL = "ROOM_FULL",
  ROLE_ALREADY_USED = "ROLE_ALREADY_USED",
  INVALID_ROLE = "INVALID_ROLE",
}

export enum ProductErrorCode {
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_MISMATCH = "ROOM_MISMATCH",
  INVALID_ROLE = "INVALID_ROLE",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
}

export enum DiscountErrorCode {
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_MISMATCH = "ROOM_MISMATCH",
  INVALID_ROLE = "INVALID_ROLE",
  INVALID_TYPE = "INVALID_TYPE",
  INVALID_VALUE = "INVALID_VALUE",
  LABEL_REQUIRED = "LABEL_REQUIRED",
}
